### ISSUE TITLE
Collect multiple FritzBox-Data

### ISSUE THREAD

**Issue by obkgroove21** [jammsen/docker-collectd-fritzbox#2]
Hey there,

everything is working for one FritzBox. Is is possible to collect several fritz box instances and specify them by a unique hostname?
Which enviroments variables should be used for other instances?

Greetings :)

**Comment by jammsen** [comment]
Hey @obkgroove21 
i dont have another Fritzbox, so i cant try it out. but you could create another database and just add another docker-container which in return uses that other database. After that add that other databse in Grafana. I guess that could work.

The definition for that in InfluxDB you can find here afaik:
https://github.com/jammsen/docker-collectd-fritzbox/blob/master/influxdb.conf#L109
