### ISSUE TITLE
add: Grafana 1s refresh intervall 

### ISSUE THREAD

**Issue by JuXReal** [jammsen/docker-collectd-fritzbox#3]
Hello, 
Grafana change the default possibility for 1 Sec. intervalls. 

Where to place this Command to bring it back? 

Docker run -e GF_DASHBOARDS_MIN_Refresh_INTERVAL=1S grafana

**Comment by jammsen** [comment]
Hey @JuXReal 
i guess you could add an enviroment definition on the docker-compose file under grafana part:
https://github.com/jammsen/docker-collectd-fritzbox/blob/master/docker-compose.yml#L5

**Comment by jammsen** [comment]
Closed for inactivity
